# -*- coding: utf-8 -*-
"""FileConversion .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IEMbbeAfOtpq5lNRtV1_sbezzx3r_h7e
"""

import cv2 
import numpy as np 
import matplotlib.pyplot as plt 

# This is a magic command to display in an external window 

image = cv2.imread("Electrical_Energy_Prod_Cons.png", 1) 
# Loading the image 

half = cv2.resize(image, (0, 0), fx = 0.2, fy = 0.2) 
bigger = cv2.resize(image, (1050, 1610)) 

stretch_near = cv2.resize(image, (1080, 1600), 
			interpolation = cv2.INTER_NEAREST) 


Titles =["Original", "Half", "Bigger", "Interpolation Nearest"] 
images =[image, half, bigger, stretch_near] 
count = 4

for i in range(count): 
	plt.subplot(2, 2, i + 1) 
	plt.title(Titles[i]) 
	plt.imshow(images[i]) 

plt.show()

import scipy.io
import pandas as pd

mat = scipy.io.loadmat('TestValues.mat')
mat = {k:v for k, v in mat.items() if k[0] != '_'}
data = pd.DataFrame({k: pd.Series(v[0]) for k, v in mat.items()})
data.to_csv("example.csv")

